version: "3.7"

services:
  fastapi_service:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    environment:
      - DOCKER_ENV=1

  db_postgres:
    image: postgres:16-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./scripts/create_databases.sql:/docker-entrypoint-initdb.d/init.sql
      - project_root/
      - secret/
        - .env
        - .env.docker

volumes:
  db-postgres:
    driver: local



  
